---
- name: copy all the checks files
  copy:
    src=sensu/plugins/
    dest=/etc/sensu/plugins/
    owner="{{ sensu_user }}"
    group="{{ sensu_group }}"
    mode=0750

- name: Install dependencies for adding new Ruby Gems
  yum: name={{ item }} state=installed
  with_items:
    - gcc
    - gcc-c++
    - make
  when: ansible_os_family == "RedHat"

- name: Install Sensu Community Monitoring Gems
  gem: name={{ item }} state=latest executable=/opt/sensu/embedded/bin/gem user_install=no
  with_items:
    - sensu-plugins-disk-checks
    - sensu-plugins-load-checks
    - sensu-plugins-memory-checks
    - sensu-plugins-process-checks
    - sensu-plugins-network-checks
    - sensu-plugins-cassandra
    - sensu-plugins-raid-checks

- name: Install Gems Dependencies for Custom Checks
  gem: name={{ item }} state=latest executable=/opt/sensu/embedded/bin/gem user_install=no
  with_items:
    - rest-client

- name: generate config files
  template:
    src=client.json.j2
    dest=/etc/sensu/conf.d/client.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  notify:
    - restart sensu client

- name: enable sensu-client to survive reboot
  service:
    name=sensu-client
    enabled=yes
    state=started
